name: 'Tips Action'

description: 'Post a random tip to the specified Slack channel'

outputs:
  random-tip:
    description: "Random tip"
    value: ${{ steps.random-tip.outputs.tip }}

runs:
  using: "composite"
  steps:
    - id: random-tip
      run: |
        tipname=$(jq -r 'keys[]' tips.json | shuf | head -n 1)
        echo $tipname
        tip=$(jq -r ."\"$tipname\"" tips.json)
        echo $tip
        echo "::set-output name=tip::$(echo $tip)"
      shell: bash