name: Post a random tip to Slack

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "0 9 * * 1"  # This runs at 9 am UTC every Monday

jobs:
  post-tip:
    runs-on: ubuntu-latest
    name: Pick and post a random tip to Slack
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Pick a random GitHub tip
        id: pick-tip
        uses: some-natalie/github-tips-action@v0.0.2

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: "{\"blocks\":${{ steps.pick-tip.outputs.tip }}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
