name: Post a random tip to Slack

on: 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  post-tip:
    runs-on: ubuntu-latest
    name: Pick and post a random tip to Slack
    steps:
      - uses: actions/checkout@v2
      - id: random-tip
        uses: ./
      - name: test
        run: echo ${{ steps.random-tip.outputs.tip }}
        shell: bash
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[${{ steps.random-tip.outputs.tip }}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK